local a = {}
a["data"] = {}
a["data"]["number_of_all_deals"] = 1
a["data"]["total_profit"] = 0
a["data"]["work_date"] = "20170126"
a["SRH7 SPBFUT"] = {}
a["SRH7 SPBFUT"]["last_price"] = 17275
a["SRH7 SPBFUT"]["total_profit"] = 0
a["SRH7 SPBFUT"]["deal"] = {}
a["SRH7 SPBFUT"]["deal"]["open_date"] = 20170125
a["SRH7 SPBFUT"]["deal"]["class_code"] = "SPBFUT"
a["SRH7 SPBFUT"]["deal"]["deal_direct"] = "b"
a["SRH7 SPBFUT"]["deal"]["open"] = true
a["SRH7 SPBFUT"]["deal"]["avg_price"] = 17219
a["SRH7 SPBFUT"]["deal"]["transactions"] = {}
a["SRH7 SPBFUT"]["deal"]["transactions"][1] = {}
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["flags"] = 64
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["class_code"] = "SPBFUT"
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"] = {}
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["week_day"] = 3
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["hour"] = 21
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["min"] = 53
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["mcs"] = 99000
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["year"] = 2017
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["month"] = 1
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["sec"] = 49
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["day"] = 25
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["datetime"]["ms"] = 99
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["price"] = 17219
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["qty"] = 1
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["sec_code"] = "SRH7"
a["SRH7 SPBFUT"]["deal"]["transactions"][1]["ordernum"] = 24703222829
a["SRH7 SPBFUT"]["deal"]["sum_contracts"] = 1
a["SRH7 SPBFUT"]["deal"]["sec_code"] = "SRH7"
a["SRH7 SPBFUT"]["number_of_deals"] = 1
a["SRH7 SPBFUT"]["profit"] = 56
a["SRH7 SPBFUT"]["total_qty"] = 1
return a
